### ISSUE TITLE
Server crashes after downloading the server files, pressing L in the server list and joining

### ISSUE THREAD

**Issue by LeComm** [iamgreaser/iceball#102]
I downloaded the latest server files (including svsave) from this github thingy, started the server list, pressed L and after the client localhost-connected, everything crashed.
The console says following:
Lua Server Error (tick): pkg/base/network.lua:595: attempt to concatenate a boolean value
I don't have any experience with lua, but after messing with the code, I found out that (#"..cli.plrid..", neth "..(neth or "nil")..") seems to cause the problem. Might also be me being a noob?

**Comment by rakiru** [comment]
You will also need a config file. Grab svsave from github too.

**Comment by LeComm** [comment]
I already have

**Comment by iamgreaser** [comment]
Ah right, I forgot to push a fix for that. I'll close this once this is sorted.

**Comment by iamgreaser** [comment]
Fix should be pushed now. Closing. If it isn't pushed, feel free to reopen.
