### ISSUE TITLE
Handle more than 9 servers on the launcher

### ISSUE THREAD

**Issue by iamgreaser** [iamgreaser/iceball#105]
While this would result in us forfeiting our Cirno Seal of Approval, we do need to be ready for this.

**Comment by rakiru** [comment]
Pages, 9 servers on each. Numpad support would be nice too, if anyone does anything on this.

**Comment by Dany0** [comment]
easiest (temporary) solution, add scrolling like /iceball/halp

**Comment by iamgreaser** [comment]
Been sorted. Closing.
