### ISSUE TITLE
Second buffer for UI stuff

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#110]
Currently the tool selection thing plops up in the actual game world, and so is bound to render through blocks, to mitigate this there should be support for a 3d-in-2d alternate buffer for HUD stuff. In other words, a second camera that renders the HUD stuff.

Not for the player/tools mind you, because we might want the spade animation to clip through blocks.

**Comment by iamgreaser** [comment]
Actually the ideal way to implement this is to just have something like client.clear_depth() which just calls glClear(GL_DEPTH_BUFFER_BIT).

It's simpler than you think.

**Comment by iamgreaser** [comment]
client.gfx_clear_depth() is a thing now.
