### ISSUE TITLE
Particle models don't get disposed of?

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#113]
I did this to obj_particle

			if not this.model then
				common.model_free(mdl_particle)
				error("this works")
			elseif this.free_model then
				common.model_free(this.model)
				error("stuff")
			end

used the rifle a bit, exploded a few grenades... switched teams all that, left it running in the background for 30 minutes then quit it didn't error once

EDIT:
So, as I understand this now, GC is implemented but not all of the code was accustomed to it?

**Comment by iamgreaser** [comment]
We have garbage collection, so model_free is a no-op now.

If you absolutely positively have to remove something from memory, make sure nothing references it, and then do collectgarbage().
