### ISSUE TITLE
New font

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#115]
Before the event we need one more thing - get a better (number) font. Because you guys liked futura, I suggest [this free clone](http://en.wikipedia.org/wiki/Beteckna), though I don't know how it'd loo... oh who am I kidding, it'd look something(?) like this:
![](https://dl.dropboxusercontent.com/u/18131766/ShareX/2015/02/2015-02-05_03-00-192.png)

Also, unrelated but related but I'm too lazy and  really need sleep for another issue...

It'd be better to turn off the network meter for noobs, or at least move it halfway between the map and ammo label and make it maybe 96x48 pixels, so that it isn't distracting by default. 

It's totally distracting if you don't know what it is, when suddenly you have this graph buzzing around.

Also to put the graph drawing thing to good use, it could display how close each team is/was to winning from game start to end(or just since connecting). EDIT: I mean when you press tab.
Intels captured shouldn't be hard to implement. Though that wouldn't be too eventful of a graph, now number of kills per team, that's something interesting.

Oh, and last sidetrack, for the event server, replace "If it's broken fix it yourself" with something charming and joyful and I'm going to bed.

**Comment by rakiru** [comment]
New font added in b95928180883b98f03f1fd730fd46a891835f7e6
