### ISSUE TITLE
Weapons can be refilled only once at the tent

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#118]
You can only refill the shotgun ammo at the tent once, after you do it won't refill.

EDIT:
rak's right, I was under the impression that the other guns don't have this problem.

**Comment by rakiru** [comment]
There is no code in the shotgun mod to deal with this, so it would be a bug in the base game. You can only restock if you can restock on blocks. I'm not sure if this is intentional, and if it is, if we want to keep it, but that's how restocking on all weapons works at the moment.

**Comment by rakiru** [comment]
It's not that they can only be refilled once; it's that they can only be refilled as long as blocks need refilled. Whether or not this is intended/wanted should be decided quickly and sorted either way though.

**Comment by rakiru** [comment]
Ok, this is related to the grenade not showing problem. Ammo isn't synced on the server any more/currently, so the gun never needs restocked. I'll try and get a little fix in there for that now.

**Comment by rakiru** [comment]
Typoed commit message apparently... closes #118*

**Comment by rakiru** [comment]
That was just a quick-fix for the current framework. #117 should do it properly (i.e. actually care if a client runs out of bullets but is still telling us they're firing).
