### ISSUE TITLE
Refresh the server list in the launcher

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#122]
1. force refresh by pressing R
2. auto-refresh every 30 secs?

**Comment by rakiru** [comment]
I'd say no to auto-refresh (what if you're looking through pages?), but R to refresh would be a good idea.

**Comment by LeComm** [comment]
Or just make auto-refresh configurable

**Comment by rakiru** [comment]
Could do, but when are you ever staring at the serverlist long enough that you need it to refresh itself every 30 seconds? Other than when looking through pages, which could become reordered (especially if you sort by playercount or ping or something), I can't think of a time.

If we added server querying, so you could ask the server what the current map, playercount, etc. is, then an auto-refresh for that information could work (re-query servers on the current page if they're 30+ seconds out of date).
