### ISSUE TITLE
Improved Sounds

### ISSUE THREAD

**Issue by Warp00** [iamgreaser/iceball#123]
As discussed, we need better sounds, walking first and then Weapons.

I'm looking into it, will report back.

One possibility is that we use sounds from https://github.com/yvt/openspades, however this does depend on licensing.

**Comment by Dany0** [comment]
yvt's protecting his resource pack

we can ask but I don't think he'll answer positively

**Comment by Warp00** [comment]
Probably not.

I've asked the people here http://www.freesfx.co.uk/soundeffects/footsteps/ if we can use their songs in this project as their licensing is unclear. I imagine not, but I'm not sure. IF YVT can use differently licensed sounds, so can we.

**Comment by iamgreaser** [comment]
But... beatboxsteps...

I have cellphone recordings of a .22 and a shotgun which may or may not be usable (seriously, a .22 sounds amazing) - there may have been too much wind.

**Comment by Warp00** [comment]
For guns, these are the place to go: http://freefirearmsfx.com/firearm-sound-library/4582574710
They are v.high quality, I have worked with them before. Licensing is fine.

Goodnight :)

**Comment by rakiru** [comment]
@iamgreaser The shotgun video you sent me was way too bad to use as a sound effect. If the .22 was anything like it, it's probably not good enough either.

For the shotgun mod, I mixed a few CC0 sounds I found online. I will probably redo it a bit, especially since I want a different sound for alt-fire.

**Comment by rakiru** [comment]
We got new sounds.
