### ISSUE TITLE
Launcher path problems

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#126]
It seems if the path is too long, or more likely if the path contains spaces, and you launch the iceball.exe on windows *not by command line* then choosing a server(or config) will fire iceball -h because the params are wrong it seems.

*Needs to be fixed before the event*

**Comment by Dany0** [comment]
Here's what's the difference between launching by clicking and cmd-line:

Double clicking on windows (8.1):

    argv0: [D:\GitHub\iceball\iceball.exe]
    argv1: -s
    argv2: 0
    argv3: pkg/iceball/config

Launching from cmd-line:

    argv0: [iceball.exe]
    argv1: -s
    argv2: 0
    argv3: pkg/iceball/config

**Comment by Dany0** [comment]
```
argv: [0] C:\Microsoft
argv: [1] Dynamics
argv: [2] CRM
argv: [3] SDK\SampleCode\CS\QuickStart\drinko\iceball.exe
argv: [4] -s
argv: [5] 0
argv: [6] pkg/iceball/config
```

**Comment by iamgreaser** [comment]
This is not going to be fixed before the event. Windows' shittiness is just too pervasive to make a workaround in that time.
