### ISSUE TITLE
Compiling issues on Linux

### ISSUE THREAD

**Issue by MajorLunaC** [iamgreaser/iceball#131]
I'll advertise this game as soon as I can actually get it to work. I keep getting more and more errors as I keep trying again and again with small changes. This is using Cmake.

*Here are some solutions I managed to find so far:

In /iceball-master/include/common.h

- Change

#include \<SDL.h>

TO

#include \<SDL/SDL.h>

- Change

#include <sackit.h>

TO

#include <../xlibinc/sackit.h>

Ideally, put a copy of sackit in iceball to compile just before the rest of iceball source.

*Linker flags are a total mess. To fix just some of them, I had to manually add the following:

-lGLEW -lGL -lm -ldl -fopenmp -libpng -lenet

I think the -libpng might need a version number with it though. And I still get errors everywhere, which makes me question, is this game 32-bit only? Nowhere along the way during compiling or anywhere here does it mention it if so. And it would really suck.

More of the errors if anyone is interested: http://pastebin.com/kSWdh76k

*I also tried with the original Makefile (which is overwritten by cmake if running cmake . ) which has most of those linker flags, but I don't think it can find lua:

No package 'lua-5.1' found
Package lua5.1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `lua5.1.pc'
to the PKG_CONFIG_PATH environment variable
undefined reference to `lua_createtable'

I have lua 5.1 in /usr/lib64 , and I even made an extra link ( ln /usr/lib64/liblua-5.1.so /usr/lib64/liblua5.1.so ) which is known to cause problems if missing.

**Comment by iamgreaser** [comment]
For the include changes: **FUCK NO. HELL FUCKING NO. CHANGE THOSE BACK.**

CMake was for learn_more's personal MSVC Win32 builds. Use make.

If it complains about lua-5.1 *AND* lua5.1 missing then it can't find it. I'm just doing pkg-config twice for the cflags and libs, because Debian likes to do things one way and FreeBSD likes to do it another way.

We don't use libpng, we use a custom PNG loader that relies on zlib, plus even if we did you'd do -lpng, not -libpng.

The software renderer is not actually available from 0.1.2-11 onwards.

**Comment by MajorLunaC** [comment]
All right, but it continues despite not finding lua (should have stopped there), so every single function call: http://pastebin.com/SJas2E1B

Yeah, and please warn somewhere about using make and not CMake for Linux.

**Comment by iamgreaser** [comment]
OK, that's genuinely not finding Lua.

Look in these places for something that looks a little bit like a thing for Lua 5.1:
* /usr/lib/pkgconfig/
* /usr/lib64/pkgconfig/
* /usr/local/lib/pkgconfig/
* /usr/local/lib64/pkgconfig/

Let me know the filename and I'll add it to the list.

Alternatively you could modify the Makefile to point to the right place.

**Comment by MajorLunaC** [comment]
lua.pc in /usr/lib64/pkgconfig/

**Comment by rakiru** [comment]
All mention of CMake was removed from the README.txt because it's outdated. That's why it only mentions the Makefiles.

**Comment by iamgreaser** [comment]
I'll sort that case out once I have time.

**Comment by iamgreaser** [comment]
Should be sorted in 0.2.1 - if not, check the new findlua.sh and make it work.

**Comment by MajorLunaC** [comment]
Yup, it works now. Apart from not finding everything on the first attempt of run.sh with option 1) Single-player, it did manage to work with option 3) Lighting test, and then option 1 worked on the next run.
First run of option 1) Single-player output: http://pastebin.com/azBPHz1r

**Comment by rakiru** [comment]
Oh yeah, the start scripts should probably be removed. They are there from before we had a launcher, and when the software renderer still existed.

**Comment by iamgreaser** [comment]
What rakiru said.

Anyway, problem solved, so closing!

**Comment by nifker** [comment]
I try to compile it too - but can someone tell me what installpath I should choose for sackit?

**Comment by iamgreaser** [comment]
After building sackit, copy `libsackit.a` and `sackit.h` to `iceball/xlibinc/` (the directory should exist when you get Iceball from Git).

Don't worry if sackit spews errors, if `libsackit.a` exists, it built. (Running `make` for sackit will build the library and then a bunch of test programs which Iceball doesn't need.)
