### ISSUE TITLE
No "io"

### ISSUE THREAD

**Issue by LeComm** [iamgreaser/iceball#147]
I was going to add output showing the current map generating progress, because it takes so long.
But I found out that there's no access to the "io" module.

**Comment by rakiru** [comment]
`print("derp herp")`

**Comment by iamgreaser** [comment]
There's a reason I don't allow access to the io module.

So yeah, use print() instead.

Closing.

**Comment by LeComm** [comment]
(I was aware of print, the problem lied in fflush)
