### ISSUE TITLE
Update to Lua 5.3

### ISSUE THREAD

**Issue by rakiru** [iamgreaser/iceball#148]
This should be fairly straight-forward on the engine side, but may break a bunch of the game code. It has a bunch of useful feature additions though, and has the convenient bonus of fixing the print-not-flushing issue.

**Comment by sillesta** [comment]
What implications will this have on using luajit? (iirc luajit only supports 5.1 with *some* features from 5.2)

**Comment by rakiru** [comment]
The implications will be that we'll go from almost-certainly-never-using-luajit to certainly-never-using-luajit. This ticket isn't a definite plan, but 5.3 has a bunch of nice things (as well as a few nice 5.2 things).

**Comment by rakiru** [comment]
We're not switching. The int thing alone would cause a ton of refactoring, and there were some other concerns. We discussed this on IRC at some point ages ago...
