### ISSUE TITLE
Long horizon feature list

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#152]
Let's say this is milestone 0.6. Let's call this the "direction" for iceball @rakiru was looking for.

 - Machinima mode (something like mediatracker in trackmania) (edit: Serious_Sim mentioned the "GTA4 clip editor")
  - https://www.youtube.com/watch?v=ZDNt8d6RHDg
  - What do we need:
  - A timeline
  - Complete control over what is happening on the screen
  - Ability to record and replay gameplay (regardless of mod preferably)
  - Autonomous AI would be a help
  - And of course, export to AVI/other format
 - Autonomous AI (bots)
  - Possible right now, but would probably require C code to make it fast
  - An AI framework would be nice
 - A new, fully-fledged GUI system including a GUI editor
 - Complete the client launcher
  - Config
  - Server launcher and config
  - Map selection, not necessarily for server admins, I've already started work on this one so I'll assign myself to this
 - In-game IDE
  - In lua should be easy to just reset the global state
  - Would ease mod development
  - Could complement "machinima mode" development
 - Even better player/entity/weapon models, see #11
  - So (I believe) we've moved past "placeholder" models
  - But still, we need nicer, better fitting models and one, coherent graphics style
 - Drowning, see #151
 - Multiple water levels, would nicely complement drowning

Even further down the line, somewhere in space:
 - We might need a new, sandboxed and encrypted file system, if security concerns become overwhelming
 - Customize lua, forbid some crazy stuff, build-in things that we use regularly. I personally wouldn't mind a new keyword, something like "entity" *(not *object* mind you) that would translate to function foo() this = {} . We can probably go a long way before we need this though.

EDIT:
Don't mind me just typing out stuff I can do so that I can keep up with one-commit-a-day:

 - Loading image and music server setting
 - Map picker
 - Add more stuff to the config, like a crosshair selector
 - Add more stuff to launcher, like help and buttons and whatnot
 - IRC client or some other form of chat/support in the launcher
 - Finish territory control
 - Finish dig dug
 - Add clickable buttons to the gui lib
 - PNG sights
 - Move citygen and gen maps to pkg/maps
 - Userblocks maybe?
 - Improve docs, maybe add my debug workflow
 - Port zombies
 - Port Triplefox's mapgen
 - Use VA in BR's snake
 - Add more guns
 - Improve walking physics
 - Build mode
 - Jumpmap mode
  - Port checkerrace

**Comment by rakiru** [comment]
This doesn't really suit an issue tracker. Each of these things should be separate tickets.

**Comment by LeComm** [comment]
I don't like the idea of recording either. It doesn't fit the game imho.

**Comment by rakiru** [comment]
Why not? How does the whether or not players should have ability to record something depend on the type of game?

Dany0, that would be hard to do though, considering how different every mod can make it, and how much they're updated. Really, the only way to record gameplay is with a screen recorder.

**Comment by Dany0** [comment]
How to do it:
#1. Hack way
 - record packets to file
 - replay packets on server while loading all needed mods
#2. Proper way
 - add record() function to "entity" template, relay output to Recorder class
 - mods must support recording accordinly
 - replay using the custom recording format

**Comment by rakiru** [comment]
1) All needed mods at correct versions. You'd have to store the mods alongside the recording or something (no guarantee they're from github).

2) That breaks as soon as any mod doesn't support it.

**Comment by rakiru** [comment]
Closing as not a proper issue, as discussed on IRC. Feel free to split it into separate tickets.
