### ISSUE TITLE
Change kick_on_join to "first_run" or "has_played_iceball_before" something of that ilk

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#156]

**Comment by rakiru** [comment]
Why? "kick on join" is exactly what it does (when enabled, which it isn't).

**Comment by rakiru** [comment]
Closing as you want a separate setting for something else, not to simply rename the existing one.

**Comment by Dany0** [comment]
To clarify:
Just rename the param, for now the functionality will stay the same.

The reasoning is, "kick_on_join" is for server admins who don't want newbies (eg. didn't touch their config), and they might have good reasons for that (not just malicious ones). If we're going to have a (complete) GUI config, changing the config will be much easier (if not forced) and so the functionality would be effectively deprecated.

By changing the meaning behind the value, we can make better use of it. It would nicely complement "tutorial" functionality, so that it is forced on newcomers. It also means we can quantify better who is a newbie and who is not, it could be complemented for example by joined_server_count or launched_game_times, hitting zero would be counted as "no longer a complete noob".

Of course, we could just have both values, and later deprecate "kick_on_join".


Sorry if it doesn't make sense, 3am writing it is hard to keep thoughts in line.

**Comment by rakiru** [comment]
The functionality being deprecated would mean the removal of the setting. There is no use changing it entirely, and is simply confusing for users; some people mysteriously don't get any help prompts, even though they've never disabled them. As for a disable tutorials setting, I commented in the other ticket about how I think would be a better way to go about this.

`joined_server_count` or `launched_game_times` are also both pretty useless, as you can set them to whatever you like. Things like this would be best done serverside with an auth system.

**Comment by Dany0** [comment]
Alright, brain fart, sorry.
