### ISSUE TITLE
Make model outline actually an outline

### ISSUE THREAD

**Issue by rakiru** [iamgreaser/iceball#171]
At the moment, the "outline" on team mates and objectives is simply a semi-transparent scaled-up version of the model, which looks broken on a lot of models (for example, the flag). This should be made an actual outline.

![Flag outline problem](https://dl.dropboxusercontent.com/u/7298729/iceball/flag%20outline%20problem.png)

I had a look around, and these are commonly suggested methods:
* http://www.flipcode.com/archives/Object_Outlining.shtml
* http://stackoverflow.com/a/12924272/341673

I don't really know OpenGL, so I'm not sure if that second method would require a shader or not, but they were usually mentioned.

**Comment by iamgreaser** [comment]
Added an "inscale" argument to the kv6 loader and made the intel and tent objects use a model which uses it. Player object would be a pain in the arse for now. Should we close this and just wait until FBOs + shaders are in place before we attack this more... shaderly?

**Comment by NotAFile** [comment]
The outlines look correct currently, is this fixed?

**Comment by iamgreaser** [comment]
FBOs + shaders are actually in place as well, even though we don't use it for this thing.

I think the players are KV6s now.

Yeah I think this is fixed and in severe need of closing.
