### ISSUE TITLE
Separate volume controls

### ISSUE THREAD

**Issue by rakiru** [iamgreaser/iceball#175]
There should be separate volume controls (as well as the current master setting) for sound effects and music. I'm not sure if tracker music is actually louder than everything else atm, or if that can be easily balanced otherwise, but separate controls for wav "music" and tracker music may be a good-to-have too.

**Comment by iamgreaser** [comment]
Currently client.mus_vol_set allows you to set the music volume relative to the master volume, which would be a clsave/pub/user.json thing.

The volume there also appears to be completely independent of the sample master volume.

I'm going to apply a fix to this.
