### ISSUE TITLE
gl_flip_quads works not fully

### ISSUE THREAD

**Issue by JackLast** [iamgreaser/iceball#187]
when the option "gl_flip_quads" in the file iceball/clsave/config.json is set up to true,
it applies for one of the sides only, for each dimension
it does affects quads on the top faces, but not the bottom ones
the same for left and right sides, and for front and back sides, only 1 of them is affected, the other is not

**Comment by Dany0** [comment]
https://github.com/iamgreaser/iceball/blob/master/src/gl/render.c#L1065

Looking at the code it seems it should work.

**Comment by iamgreaser** [comment]
https://github.com/iamgreaser/iceball/blob/master/src/gl/render.c#L1186

It's a bug. Thanks, I'll sort it out.
