### ISSUE TITLE
New movement physics, animation

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#204]
This talk is a nice summary (just 20 mins, watch it):
http://www.gdcvault.com/play/1020583/Animation-Bootcamp-An-Indie-Approach

Note: I'm focusing on other stuff, if I'll be back it'll be a few months. Feel free to PM me on bns or something.

EDIT: This is interesting too: http://www.gamedev.net/blog/832/entry-2261013-the-poor-mans-character-controller/

**Comment by rakiru** [comment]
Once again, at the very least, give your opinions on what the movement system should be like. Stop saying "we need better movement physics" but giving no real comments on what that entails.

**Comment by iamgreaser** [comment]
Too vague. Closed.
