### ISSUE TITLE
RPG

### ISSUE THREAD

**Issue by epicfacethe3rd** [iamgreaser/iceball#216]
I've noticed that there seems to be a lot of people saying that they won't put in an RPG / grenade launcher, as there are no models.
i give you models for both:
https://sites.google.com/site/aceofspadesmods/weapon-mods
http://forumarchive2.spadille.net/viewtopic.php?f=71&t=10276&hilit=rpg&sid=c20221c96bc8ecabebb26bdd9c3aea52
you're welcome.

**Comment by rakiru** [comment]
I haven't seen anybody say that. Also, we need models that we can use with permission.
