### ISSUE TITLE
Where does the JSON code come from?

### ISSUE THREAD

**Issue by Danfun64** [iamgreaser/iceball#222]
The JSON license is considered nonfree by the FSF because of the infamous "Do No Evil" clause. It should be replaced with a different implementation than the json.org one.

**Comment by rakiru** [comment]
I'm not sure what you're talking about. `src/json.c` has a GPLv3 header comment.

**Comment by iamgreaser** [comment]
It's not the json.org one, it's one I wrote myself. The JSON saver was written by BR.

What the hell makes you think it's the json.org one?

**Comment by iamgreaser** [comment]
Also closing because This Is Complete Bullshit.
