### ISSUE TITLE
Set OpenGL 2.0 as the minimum requirement

### ISSUE THREAD

**Issue by fkaa** [iamgreaser/iceball#228]
OpenGL 2.0 came out in 2004 (12 years ago!) and has been used as a minimum requirement for years by tons of low-end games. [Statistics](http://feedback.wildfiregames.com/report/opengl/feature/GL_VERSION) show that <2.0 is miniscule, and most cards that are in that category are old as stone.

Bumping the requirement would result in more maintainable and cleaner code.

**Comment by iamgreaser** [comment]
I approve of this message.

Seriously, anything that doesn't support GL 2.0 is too shit to handle this game.

**Comment by fkaa** [comment]
Fixed by #235.
