### ISSUE TITLE
Replace GLEW dependency

### ISSUE THREAD

**Issue by fkaa** [iamgreaser/iceball#229]
Unbuildable, broken, bloated.

Personally I would prefer using a loader generator like [glLoadGen](https://bitbucket.org/alfonse/glloadgen/wiki/Home) or [glad](http://glad.dav1d.de/) which would completely drop a external dependency :+1: (you bundle the `.c/.h` pair in the project instead)

**Comment by fkaa** [comment]
There are also no distributed binaries for MinGW, which makes it a PITA to work with.

**Comment by rakiru** [comment]
There's also libepoxy, which grease has used before. AFAIK it can be built with MSVC.

**Comment by fkaa** [comment]
I looked at it, but it uses Automake and not CMake :-1: Also can't find any MSVC project files. This is why I prefer to use generators for this. They achieve the same goal (both are essentially a `.c` and a `.h` and they don't depend on any libraries or build process.

**Comment by iamgreaser** [comment]
glLoadGen and glad both look good so pick one and beat that GLEW chick before it hatches.
