### ISSUE TITLE
Ubuntu (12.04) needed tuning for makefile for Lua

### ISSUE THREAD

**Issue by aapo** [iamgreaser/iceball#23]
Error was:

    fatal error: lua.h: No such file or directory

Fix was:

    index 4ed1129..53c4a56 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -4,6 +4,7 @@ CFLAGS = -pg -O2 -fno-strict-aliasing -g `sdl-config --cflags` -Wall -Wextra \
            -Wno-unused-variable -Wno-unused-parameter \
            -Wno-unused-but-set-variable $(CFLAGS_EXTRA) \
            -I $(INCDIR) \
    +       `pkg-config --cflags lua5.1` \
            $(HEADERS_LUA)
     
     # Uncomment this if your are are Debian or Debian-derived
    @@ -11,7 +12,7 @@ HEADERS_LUA = #-I /usr/include/lua5.1
     
     LDFLAGS = -pg -g $(LDFLAGS_EXTRA)
     LIBS_SDL = `sdl-config --libs`
    -LIBS_Lua = -llua
    +LIBS_Lua = `pkg-config --libs lua5.1`
     # Lua is not an acronym. Get used to typing it with lower case u/a.
     LIBS_zlib = -lz
     LIBS = -lm $(LIBS_Lua) $(LIBS_SDL) $(LIBS_zlib)

**Comment by iamgreaser** [comment]
This is mostly in place, although we'll need some way to determine whether the package is called lua5.1 (Debian uses this) or lua-5.1 (FreeBSD uses this). Because I use FreeBSD I'm defaulting it to the latter, but we do need to check both.

**Comment by iamgreaser** [comment]
We're checking both. It spews the same pkg-config error over and over again, but it works. Closing.

**Comment by TriBlade9** [comment]
Having trouble with this as well.

**Comment by iamgreaser** [comment]
Well the patch in question is pretty much applied, so you should just do

    sudo apt-get install liblua-5.1-0-dev

and try again.

**Comment by TriBlade9** [comment]
Already done, I'll try re-cloning the repo for a fresh start. I'm on Ubuntu 14.10, liblua5.1-0-dev.

**Comment by aapo** [comment]
Hi,  "lua5.1" is correct form. "lua-5.1" is wrong.

    diff --git a/Makefile b/Makefile
    index 1ab3e21..fcce1fc 100644
    --- a/Makefile
    +++ b/Makefile
    @@ -13,12 +13,12 @@ CFLAGS = -fno-strict-aliasing -g `sdl-config --cflags` -Wall -Wextra \
     
     HEADERS_SDL = `sdl-config --cflags`
     HEADERS_ENet = `pkg-config libenet --cflags`
    -HEADERS_Lua = `pkg-config lua-5.1 --cflags` `pkg-config lua5.1 --cflags`
    +HEADERS_Lua = `pkg-config lua5.1 --cflags` `pkg-config lua5.1 --cflags`
     
     LDFLAGS = -g -I/usr/local/include $(LDFLAGS_EXTRA) 
     LIBS_SDL = `sdl-config --libs`
     LIBS_ENet = `pkg-config libenet --libs`
    -LIBS_Lua = `pkg-config lua-5.1 --libs` `pkg-config lua5.1 --libs`
    +LIBS_Lua = `pkg-config lua5.1 --libs` `pkg-config lua5.1 --libs`
     # Lua is not an acronym. Get used to typing it with lower case u/a.
     LIBS_zlib = -lz
     LIBS_sackit = xlibinc/libsackit.a

**Comment by rakiru** [comment]
@aapo 
"lua5.1" is correct on Debian-based distros, but "lua-5.1" is correct on others. Both are in the makefile so that it will work on both systems. It will complain about missing one of them, but as long as the other is there, it doesn't matter.

**Comment by TriBlade9** [comment]
@rakiru Not much to paste, it worked after re-cloning it.
