### ISSUE TITLE
(Client) can't read MapEnts from map file.

### ISSUE THREAD

**Issue by 10se1ucgo** [iamgreaser/iceball#239]
`common.map_mapents_get()` will always return `nil`. (Unless MapEnts are set in-game with `common.map_mapents_set()` and the map is not changed)

Steps to reproduce:
1. Run iceball
2. Set MapEnts with `common.map_mapents_set()`
3. Save the map
4. Notice that the MapEnts chunk is indeed inside of lastsav.icemap (hex editor or whatever).
5. Load lastsav.icemap
6. Run `common.map_mapents_get()`, it should return `nil`.

**Comment by rakiru** [comment]
<~Kasen> OH, i might know
<~Kasen> when the map is sent to the client, it just sends the current mapdata
<~Kasen> no other stuff

**Comment by rakiru** [comment]
Fixed in #264.
