### ISSUE TITLE
Set default postproc shader to "simple"

### ISSUE THREAD

**Issue by iamgreaser** [iamgreaser/iceball#243]
Maybe we need an A-config label, and/or an I-change-defaults label, because this is pretty much just a matter of changing the defaults in a config file.

As much as I like the toon shader, there are people who don't.

Begin expert opinions now.

**Comment by rakiru** [comment]
I thought I'd done this months ago, after asking you about it on IRC. My bad, must've forgot or pushed it to a scrapped branch..

**Comment by NotAFile** [comment]
Ideally you'd be able to change it in the launcher.

**Comment by rakiru** [comment]
Ideally you'd be able to do a lot of things.

**Comment by iamgreaser** [comment]
And until "ideally you'd be able to" becomes "you can", we need suitable defaults.

And even if/when that happens, we *still* need suitable defaults.

**Comment by rakiru** [comment]
The launcher can change your name already, which is in the same config file.

Since there were no complaints, changed in b659ed6bb47f50e60fcd2e85ccd28fe4d2aef8ac.
