### ISSUE TITLE
Consider using Git submodules for sackit

### ISSUE THREAD

**Issue by NotAFile** [iamgreaser/iceball#257]
Using Git submodules for including sackit should be considered. I am in the middle of making a patch to do this since it is simple, but I thought I'd start a discussion before submitting.

[Docs on Git submodules, since many people have never used them](https://git-scm.com/book/en/v2/Git-Tools-Submodules)
[and a more specific tutorial](https://chrisjean.com/git-submodules-adding-using-removing-and-updating/)

This has a couple of advantages:
- Sackit is kept up to date (almost) automatically
- Fetching the project reduced to single `git clone --recursive` command
- The sackit makefile could be run (`make -C include/sackit/`) from within the iceball makefile

In general, this would simplify building iceball on a new machine to this:
1. Install dependencies
2. `git clone --recursive git@github.com:iamgreaser/iceball`
3. `make`

Updating everything would be reduced to:
1. `git pull`
2. `git submodule update --recursive`

Caveat:

The submodule is always pointed at a specific commit and does not automatically update. This is because you might want to make changes to upstream, or are usually using a specific version or tag of the submodule. This means every time sackit is updated, you have to explicitly tell git to update the submodule.

It is explained well in the second link, but it basically boils down to:
- `cd include/sackit`
- `git checkout master`
- `git pull`

...and then committing that in iceball:master

**Comment by asiekierka** [comment]
You might want to wait on the patch. Submodules have already been brought up, and part of the team was? against it. Might be wise to hear their thoughts first.

**Comment by rakiru** [comment]
Hard -1 from me. They cause more hassle than they're worth. Even if submodules weren't landmines, in this case they don't really provide much benefit over just dumping sackit code straight into Iceball anyway.
By the way, in case you haven't seen this, if you want to do lazy/Windows dependencies, this is a thing: https://github.com/fkaa/sourceball

A better solution for sackit would be nice though.

**Comment by iamgreaser** [comment]
fkaa added a patch to sackit to add CMake support. It appears to install it for you. Perhaps we could encourage that?

**Comment by NotAFile** [comment]
Closed after discussion. Basically, many people said they are not enough benefit to warrant the pain they are.
