### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rakiru** [iamgreaser/iceball#37]
Documentation is lacking and/or outdated in many places. Changing that should be a priority.

**Comment by iamgreaser** [comment]
Closing this issue because something this vague will pretty much never be fixed. If any documentation is out of date, prod us on IRC and we can update it.

**Comment by Dany0** [comment]
Greaser's right.

I think we'll write better docs once there's a community of developers who will be bothersome enough that we'd want to RTFM them all.
