### ISSUE TITLE
/slap /nuke /piano /wobblehead

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#49]
/slap slaps players that swear, are assholes or immature, makes a noise, moves them to the side (possibly taking them out of cover/camping position/down from a high height)

/nuke throws a HK69 grenade on their position at the execution of the command that kills them and only them and destroys land around

/piano spawns a piano over them, crushing them and everyone around and playing that one awesome sad trombone sound to humiliate them

/wobblehead oversizes the player's head(incl. hitbox) and makes the face look like a crying baby

**Comment by iamgreaser** [comment]
The other three have not been worked on whenever. Closing as part of an issue purge.
