### ISSUE TITLE
Framerate degrades over time

### ISSUE THREAD

**Issue by iamgreaser** [iamgreaser/iceball#70]
Shouldn't have to say much here, but I definitely noticed it during Iceball Event 2: Event Harder.

Current workaround is to just relog.

**Comment by iamgreaser** [comment]
With the garbage collector and a bunch of fixes in place (including the fact that tracer_add never actually cleaned itself up, how did that stay there all that time?), this is still a problem.

Any ideas?

**Comment by rakiru** [comment]
This is where I would usually look at how many instances of each type exist over time, and see what keeps growing. That approach doesn't really work in Lua... Is there any way to do something similar?

**Comment by iamgreaser** [comment]
Fixed. Basically, here's what was ultimately wrong:
- tracer list wouldn't clear properly
- block health list wouldn't clear very quickly at all
- particle list wouldn't clear properly <-- this proving to be the straw that broke the camel's arsehole.

In other words it was probably all CPU-bound. Closing!
