### ISSUE TITLE
Alternative map pass the border rendering

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#81]
Some map designs may have different desires for what's rendered beyond the map border.

1. Indestructible enclosed maps will desire nothing rendered beyond the border, since you won't ever see the outsides anyway. Maybe not even indestructible maps, this simply should be an option.
2. Some maps may want just a skybox rendered.
3. Other maps may desire some kind of scenery rendered beyond the borders. See the map awp_india for an example of what I mean.

**Comment by iamgreaser** [comment]
Closing mostly for housekeeping reasons. Wraparound is deprecated and typically disabled when possible.
