### ISSUE TITLE
Dig dug

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#85]
http://www.buildandshoot.com/viewtopic.php?f=8&t=3838

So intels spawn underground and you have to dig them out.

Seems like a fun idea, could be interesting to combine with gen_flat+noise.

Or even better, let's make use of Iceball features!

1. Instead of intels, they'll be gold nuggets (colour pmf_test to yellow? :D)
2. You will only be able to see them on the map if you're close enough or if the enemy team is close enough!

**Comment by iamgreaser** [comment]
Closing - issue purge of old requests.

By the way, really sorry for the email spam.
