### ISSUE TITLE
Server IRC client

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#87]
Pyspades had this functionality and it was very popular. Maybe somewhere down the line there could be a web admin panel - game server providers love that.

lua.sockets is enough to implement that, here's an implementation in Lua I found on the net:
https://github.com/JakobOvrum/LuaIRC

I'm concerned a bit about RAM usage - as the IRC module took up a large part of pyspades usage after a long time and caused crashes.

**Comment by iamgreaser** [comment]
Going to close this and point everyone to #101, just so I don't have to close this later.
