### ISSUE TITLE
Render artifacts and pmf models wall see-through

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#9]
Render artifact:
http://j.mp/10qlOXu
close-up
http://j.mp/10qn2lQ
highlighted
http://j.mp/10qs29S

pmf wall see-through:
http://j.mp/10qnEb6
http://i.imgur.com/S1T7Hhp.png ( see in the middle? )

**Comment by rakiru** [comment]
Software renderer is ded.
