### ISSUE TITLE
Use LuaJIT

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#90]
LuaJIT is complete rewrite with a bunch of ASM optimizations. I would prefer if we used it in case some crazy server admin tries to do complex calculations in Lua (like 4d simplex noise for map generation)

Oh an it'd speed up map generation, which could be crucial if we add map switching on the go, as if it takes too long(and from pyspades I know it can take too long) clients might choose to disconnect.

**Comment by iamgreaser** [comment]
Closing because of an issue purge.
