### ISSUE TITLE
Add client option to disable (grenade) block breaking particles

### ISSUE THREAD

**Issue by ghost** [iamgreaser/iceball#92]
I was playing around with my newly aquired iceball-gl and noticed how incredibly laggy grenades are. Not because of the calculations and effects, but because of the particles generated by the block breaking.

to recreate:
1. dig a hole into a wall on a map like mesa
2. throw the grenade into the hole
3. watch the framerate drop in the lag-o-meter

I think it is possible to disable particles for a certain source, as the spade right click does not cause any particles

**Comment by iamgreaser** [comment]
Closing because of an issue purge. I stand by what I said, and if someone really wants this to be implemented they can do it themselves.
