### ISSUE TITLE
Iceball does not support foreign/mac keyboards

### ISSUE THREAD

**Issue by ghost** [iamgreaser/iceball#93]
It would seem that somehow the sdl codes are mixed up for non-us keyboards.
to help the issue, this is what the shift-number keys look like on a mac-german keyboard:
!"§$%&/()=?
here is what the game displays when I do the same thing:
!@#$%^&*()
one of the problems is that I have not been able to type a "/" at all.
I personally have no clue, I hope this gets fixed soon :)

**Comment by iamgreaser** [comment]
Works now, apparently. QWERTZ worked, plus UK QWERTY (for the most part).

Note, if it's not in ASCII, it won't work - the font only covers the ASCII set.

Closing!
