### ISSUE TITLE
Garbage collection

### ISSUE THREAD

**Issue by iamgreaser** [iamgreaser/iceball#97]
This would save us a LOT of grief, mostly pertaining to memory leaks and whatnot.

More research is necessary. I think we need to have some metatable shit in there.

**Comment by iamgreaser** [comment]
OK, this apparently is mostly in there, although maps and music I don't really care all that much about wrt GC. Should I just close this?

**Comment by rakiru** [comment]
What's the trouble with GCing music? And maps should be easy, surely? Can there be more than one?

Close it if you think it's unnecessary though; I doubt anyone else is going to get around to it any time soon.

**Comment by iamgreaser** [comment]
I've found that freeing music tends to be a bit unstable. But the thing is, there really isn't much point in GCing music and maps other than consistency - there's very few of the damn things loaded, and you generally don't unload them (aside from maps, but there's usually only one going at a time anyway).

**Comment by rakiru** [comment]
For the maps, I was wondering about when a server changes map. If the old one just hangs around, that would be an issue.
Sounds, while not really an issue for the base game, could be problematic for custom servers, so an *eventual* fix would be good.

**Comment by iamgreaser** [comment]
I'm talking about garbage collection - common.map_free() and common.mus_free() both still exist and still do things.

**Comment by rakiru** [comment]
Right, yeah, derp. That's not an issue for maps, and I guess anything that does any weird shit with a ton of music can free it itself.

**Comment by iamgreaser** [comment]
Closing because it's pretty easy to free maps and music by hand... although I'm genuinely not sure about the music but yeah.
