### ISSUE TITLE
There was a commit

### ISSUE THREAD

**Issue by Dany0** [iamgreaser/iceball#99]
What just happened.

**Comment by iamgreaser** [comment]
People gave a shit, that's what happened.

**Comment by asiekierka** [comment]
That's an issue that has to be solved immediately.

**Comment by LiquidProcessor** [comment]
soo. youre back?

**Comment by rakiru** [comment]
This is a serious issue. We can't be having any commits in this project. Thank you for bringing it to attention, Dany0 - we will rectify this immediately.

**Comment by Ericson2314** [comment]
Whoa

**Comment by LiquidProcessor** [comment]
does BnS still suck or no?

**Comment by rakiru** [comment]
More than ever.

**Comment by iamgreaser** [comment]
BnS still sucks, yeah.

**Comment by Dany0** [comment]
# Yaay \\:D/

**Comment by rakiru** [comment]
For anyone that wants to chat on IRC, the channel is `#iceball` on `irc.fractiongamers.com`([webchat](http://webchat.fractiongamers.com/?channels=iceball)).

**Comment by asiekierka** [comment]
Why was this closed? The sudden rebirth of Iceball is clearly a bug.

**Comment by rakiru** [comment]
Feel free to join IRC to discuss a solution to this major and ongoing issue.
